name: Deploy to S3
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 12
        
      - name: Install dependencies
        run: npm install
      
      - name: Build Ionic
        run: ionic build --prod
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
        
      - name: Push to S3
        run: aws s3 cp www s3://url-shortener-frontend-production --recursive